### ISSUE TITLE
Problems with overitten user template email sender

### ISSUE THREAD

**Issue by BenjaminQuandt** [RocKordier/OroBasicsBundle#18]
Hi, 

it looks like there is a bug in the bundle. A platform update fails now.

oro version: 2.6

Composer update:
- Updating ehdev/oro-basics-bundle (1.0.5 => 1.0.8): Downloading (100%) 

Error:
`[RuntimeException]
[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]                                                                               
    Unable to replace alias "oro\bundle\userbundle\mailer\usertemplateemailsender" with actual definition "oro_user.mailer.user_template_email_sender".`

`[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                                                             
    You have requested a non-existent service "oro_user.mailer.user_template_email_sender".       `
I downgraded to 1.0.3 for now to get it running.
  - Downgrading ehdev/oro-basics-bundle (1.0.8 => 1.0.3): Loading from cache

**Comment by RocKordier** [comment]
@BenjaminQuandt  should be fixed. i'll create a new release ASAP.
